# Generated by Django 5.2.1 on 2025-05-30 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='arquivo_exame',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='arquivo_exame_paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='termo_paciente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinica_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clinica', verbose_name='Clínica Principal'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.CreateModel(
            name='ExameConsultaArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='consultas_exames/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Exame da Consulta')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_consulta_arquivos', to='core.consulta')),
            ],
            options={
                'verbose_name': 'Exame da Consulta',
                'verbose_name_plural': 'Exames da Consulta',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='ExamePacienteArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='pacientes_exames/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Exame')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_arquivos', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Exame do Paciente',
                'verbose_name_plural': 'Exames do Paciente',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='TermoConsultaArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='consultas_termos/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Termo da Consulta')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_consulta_arquivos', to='core.consulta')),
            ],
            options={
                'verbose_name': 'Termo da Consulta',
                'verbose_name_plural': 'Termos da Consulta',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='TermoPacienteArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='termos_pacientes/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Termo')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_arquivos', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Termo do Paciente',
                'verbose_name_plural': 'Termos do Paciente',
                'ordering': ['-data_upload'],
            },
        ),
    ]
