# Generated by Django 5.2.1 on 2025-05-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consulta_procedimento_alter_dentista_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
