# Generated by Django 5.2.1 on 2025-05-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_consulta_pago_consulta_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='exames',
            field=models.TextField(blank=True, null=True),
        ),
    ]
