# Generated by Django 5.2.1 on 2025-05-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paciente_exames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='exames',
        ),
        migrations.AddField(
            model_name='consulta',
            name='arquivo_exame',
            field=models.FileField(blank=True, null=True, upload_to='exames/'),
        ),
    ]
