# Generated by Django 5.2.1 on 2025-05-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paciente_exames'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado'), ('NAO_COMPARECEU', 'Não Compareceu')], default='AGENDADO', max_length=20),
        ),
    ]
