# Generated by Django 5.2.1 on 2025-05-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_consulta_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='confirmada',
        ),
    ]
