# Generated by Django 5.2.1 on 2025-05-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_consulta_confirmada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['data_consulta', 'hora_inicio']},
        ),
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateField(default='2025-05-27', verbose_name='Data da Consulta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora_fim',
            field=models.TimeField(default='09:00:00', verbose_name='Horário de Fim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora_inicio',
            field=models.TimeField(default='08:00:00', verbose_name='Horário de Início'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='data_hora',
        ),
    ]
