# Generated by Django 5.2.1 on 2025-05-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_consulta_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='arquivo_exame_paciente',
            field=models.FileField(blank=True, null=True, upload_to='pacientes_exames/'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='termo_paciente',
            field=models.FileField(blank=True, null=True, upload_to='termos_pacientes/'),
        ),
    ]
