# Generated by Django 5.2.1 on 2025-05-28 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_paciente_arquivo_exame_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='exames',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clinica'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dentista'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado'), ('NAO_COMPARECEU', 'Não Compareceu'), ('RESERVADO', 'Reservado')], default='AGENDADO', max_length=20),
        ),
    ]
