# Generated by Django 5.2.1 on 2025-05-28 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_paciente_exames_alter_consulta_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='clinica_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clinica', verbose_name='Clínica Principal'),
        ),
    ]
