# Generated by Django 5.2.1 on 2025-05-28 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_paciente_clinica_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='arquivo_exame_paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='termo_paciente',
        ),
        migrations.CreateModel(
            name='ExamePacienteArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='pacientes_exames/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Exame')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_arquivos', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Exame do Paciente',
                'verbose_name_plural': 'Exames do Paciente',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='TermoPacienteArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='termos_pacientes/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Termo')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_arquivos', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Termo do Paciente',
                'verbose_name_plural': 'Termos do Paciente',
                'ordering': ['-data_upload'],
            },
        ),
    ]
