# Generated by Django 5.2.1 on 2025-05-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_paciente_arquivo_exame_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='arquivo_exame',
        ),
        migrations.CreateModel(
            name='ExameConsultaArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='consultas_exames/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Exame da Consulta')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_consulta_arquivos', to='core.consulta')),
            ],
            options={
                'verbose_name': 'Exame da Consulta',
                'verbose_name_plural': 'Exames da Consulta',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='TermoConsultaArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='consultas_termos/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Termo da Consulta')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_consulta_arquivos', to='core.consulta')),
            ],
            options={
                'verbose_name': 'Termo da Consulta',
                'verbose_name_plural': 'Termos da Consulta',
                'ordering': ['-data_upload'],
            },
        ),
    ]
