# Generated by Django 5.2.1 on 2025-05-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_consulta_arquivo_exame_exameconsultaarquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
